port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 211.137.58.20
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query
    - https://doh.opendns.com/dns-query
  fallback:
    - https://149.112.112.112:5053/dns-query
    - https://9.9.9.9:5053/dns-query
    - https://dns.quad9.net:5053/dns-query
    - tls://8.8.8.8:853
    - tcp://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4211.137.58.20
proxies:
  - {name: trojan1, type: trojan, server: ***.***.xyz, port: 443, password: mkWBSz}
proxy-groups:
  - name: 手动选择
    type: select
    proxies:
      - trojan1
  - name: 故障转移
    type: fallback
    proxies:
      - trojan1   
    url: http://www.gstatic.com/generate_204
    interval: 180
  - name: PROXY
    type: select
    proxies:
      - 故障转移
      - 手动选择
  - name: MATCH
    type: select
    proxies:
      - PROXY
      - DIRECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - PROCESS-NAME,Telegram.exe,PROXY
  - PROCESS-NAME,org.telegram.messenger,PROXY
  - DOMAIN-SUFFIX,t.me,PROXY
  - DOMAIN-SUFFIX,tdesktop.com,PROXY
  - DOMAIN-SUFFIX,telegra.ph,PROXY
  - DOMAIN-SUFFIX,telegram.me,PROXY
  - DOMAIN-SUFFIX,telegram.org,PROXY
  - DOMAIN-SUFFIX,telesco.pe,PROXY
  - IP-CIDR,91.108.0.0/16,PROXY,no-resolve
  - IP-CIDR,109.239.140.0/24,PROXY,no-resolve
  - IP-CIDR,149.154.160.0/20,PROXY,no-resolve
  - IP-CIDR6,2001:67c:4e8::/48,PROXY,no-resolve
  - IP-CIDR6,2001:b28:f23d::/48,PROXY,no-resolve
  - IP-CIDR6,2001:b28:f23f::/48,PROXY,no-resolve
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - GEOIP,AE,PROXY
  - GEOIP,AU,PROXY
  - GEOIP,BR,PROXY
  - GEOIP,CA,PROXY
  - GEOIP,DE,PROXY
  - GEOIP,DK,PROXY
  - GEOIP,ES,PROXY
  - GEOIP,FI,PROXY
  - GEOIP,FR,PROXY
  - GEOIP,GB,PROXY
  - GEOIP,GR,PROXY
  - GEOIP,HK,PROXY
  - GEOIP,ID,PROXY
  - GEOIP,IL,PROXY
  - GEOIP,IN,PROXY
  - GEOIP,IQ,PROXY
  - GEOIP,IR,PROXY
  - GEOIP,IT,PROXY
  - GEOIP,JP,PROXY
  - GEOIP,KR,PROXY
  - GEOIP,MO,PROXY
  - GEOIP,MY,PROXY
  - GEOIP,NL,PROXY
  - GEOIP,NO,PROXY
  - GEOIP,NZ,PROXY
  - GEOIP,PH,PROXY
  - GEOIP,RU,PROXY
  - GEOIP,SA,PROXY
  - GEOIP,SG,PROXY
  - GEOIP,TH,PROXY
  - GEOIP,TR,PROXY
  - GEOIP,TW,PROXY
  - GEOIP,US,PROXY
  - GEOIP,VN,PROXY
  - MATCH,DIRECT


























































